spring:
  
   application:
     name: spring boot feign producer
    
   # Excluye la autoconfiguraci√≥n de datasource realizada por Spring Boot... ya que no vamos a usar ninguna DB. 
   autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  
      
server:
   port: 8088


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic